name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag my-image-name:latest
        export TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
        docker tag my-image-name:latest my-image-name:$TIMESTAMP

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image to Docker Hub
      run: |
        export TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
        docker push my-image-name:$TIMESTAMP
