# Create and publish a Docker image
name: Create and publish a Docker image

# Trigger the workflow when the CodeQL workflow completes
on:
  workflow_run:
    workflows: ["CodeQL"]
    types:
      - completed

# Define environment variables
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    # Run the job on the latest Ubuntu environment
    runs-on: ubuntu-latest

    # Set necessary permissions
    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to the Docker registry
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Extract metadata (tags, labels) for Docker
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha
      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
